version: "2"

services:

  #php server
  php:
    build: ./docker/php
    volumes:
      - ./app:/app
    depends_on:
      - 'mysql'
    tty: true
    ports:
      - "9000:9000"
    networks:
      - local-network

  nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    links:
        - php
    volumes:
        - ./app:/app
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - public-network
      - local-network

  mysql:
    image: mariadb:10.4
    hostname: "mysql"
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - '.env'
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - local-network

volumes:
  db-data:

networks:
  public-network:
  local-network:
